### ISSUE TITLE
how to solve this problem

### ISSUE THREAD

**Issue by JamesGavin1** [jllllll/one-click-installers#1]
Starting the web UI...
  File "server.py", line 140
    return state, *[generate_params[k] for k in ['do_sample', 'temperature', 'top_p', 'typical_p', 'repetition_penalty', 'encoder_repetition_penalty', 'top_k', 'min_length', 'no_repeat_ngram_size', 'num_beams', 'penalty_alpha', 'length_penalty', 'early_stopping']]
                  ^
SyntaxError: invalid syntax

**Comment by jllllll** [comment]
No clue. This is an issue with webui and not the installer. You should open an issue about it there as I don't know enough about python to fix it. Probably just downloaded in the middle of an in-progress update.
