### ISSUE TITLE
ClobberError: This transaction has incompatible packages due to a shared path.

### ISSUE THREAD

**Issue by FarronD** [jllllll/one-click-installers#4]
Below is a transcription of the terminal output. 

This occurs after everything downloads from the install.bat file. Has happened twice now, after deleting and retrying once.

What is your GPU?

A) NVIDIA
B) None (I want to run in CPU mode)

Input> a
Packages to install: python=3.10 pytorch[version=2,build=py3.10_cuda11.7*] torchvision torchaudio pytorch-cuda=11.7 cuda-toolkit ninja git
Collecting package metadata (current_repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 23.1.0
  latest version: 23.3.1

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.3.1

## Package Plan ##

  environment location: C:\AI\one-click-installers-oobabooga-windows\installer_files\env

  added / updated specs:
    - cuda-toolkit
    - git
    - ninja
    - python=3.10
    - pytorch-cuda=11.7
    - pytorch==2[build=py3.10_cuda11.7*]
    - torchaudio
    - torchvision

The following NEW packages will be INSTALLED:

  blas               conda-forge/win-64::blas-2.106-mkl
  brotlipy           conda-forge/win-64::brotlipy-0.7.0-py310h8d17308_1005
  bzip2              conda-forge/win-64::bzip2-1.0.8-h8ffe710_4
  ca-certificates    conda-forge/win-64::ca-certificates-2022.12.7-h5b45459_0
  certifi            conda-forge/noarch::certifi-2022.12.7-pyhd8ed1ab_0
  cffi               conda-forge/win-64::cffi-1.15.1-py310h628cb3f_3
  charset-normalizer conda-forge/noarch::charset-normalizer-3.1.0-pyhd8ed1ab_0
  cryptography       conda-forge/win-64::cryptography-40.0.2-py310h6e82f81_0
  cuda-cccl          nvidia/label/cuda-11.7.0/win-64::cuda-cccl-11.7.58-0
  cuda-command-line~ nvidia/label/cuda-11.7.0/win-64::cuda-command-line-tools-11.7.0-0
  cuda-compiler      nvidia/label/cuda-11.7.0/win-64::cuda-compiler-11.7.0-0
  cuda-cudart        nvidia/label/cuda-11.7.0/win-64::cuda-cudart-11.7.60-0
  cuda-cudart-dev    nvidia/label/cuda-11.7.0/win-64::cuda-cudart-dev-11.7.60-0
  cuda-cuobjdump     nvidia/label/cuda-11.7.0/win-64::cuda-cuobjdump-11.7.50-0
  cuda-cupti         nvidia/label/cuda-11.7.0/win-64::cuda-cupti-11.7.50-0
  cuda-cuxxfilt      nvidia/label/cuda-11.7.0/win-64::cuda-cuxxfilt-11.7.50-0
  cuda-documentation nvidia/label/cuda-11.7.0/win-64::cuda-documentation-11.7.50-0
  cuda-libraries     nvidia/label/cuda-11.7.0/win-64::cuda-libraries-11.7.0-0
  cuda-libraries-dev nvidia/label/cuda-11.7.0/win-64::cuda-libraries-dev-11.7.0-0
  cuda-memcheck      nvidia/label/cuda-11.7.0/win-64::cuda-memcheck-11.7.50-0
  cuda-nsight-compu~ nvidia/label/cuda-11.7.0/win-64::cuda-nsight-compute-11.7.0-0
  cuda-nvcc          nvidia/label/cuda-11.7.0/win-64::cuda-nvcc-11.7.64-0
  cuda-nvdisasm      nvidia/label/cuda-11.7.0/win-64::cuda-nvdisasm-11.7.50-0
  cuda-nvml-dev      nvidia/label/cuda-11.7.0/win-64::cuda-nvml-dev-11.7.50-0
  cuda-nvprof        nvidia/label/cuda-11.7.0/win-64::cuda-nvprof-11.7.50-0
  cuda-nvprune       nvidia/label/cuda-11.7.0/win-64::cuda-nvprune-11.7.50-0
  cuda-nvrtc         nvidia/label/cuda-11.7.0/win-64::cuda-nvrtc-11.7.50-0
  cuda-nvrtc-dev     nvidia/label/cuda-11.7.0/win-64::cuda-nvrtc-dev-11.7.50-0
  cuda-nvtx          nvidia/label/cuda-11.7.0/win-64::cuda-nvtx-11.7.50-0
  cuda-nvvp          nvidia/label/cuda-11.7.0/win-64::cuda-nvvp-11.7.50-0
  cuda-runtime       nvidia/label/cuda-11.7.0/win-64::cuda-runtime-11.7.0-0
  cuda-sanitizer-api nvidia/label/cuda-11.7.0/win-64::cuda-sanitizer-api-11.7.50-0
  cuda-toolkit       nvidia/label/cuda-11.7.0/win-64::cuda-toolkit-11.7.0-0
  cuda-tools         nvidia/label/cuda-11.7.0/win-64::cuda-tools-11.7.0-0
  cuda-visual-tools  nvidia/label/cuda-11.7.0/win-64::cuda-visual-tools-11.7.0-0
  filelock           conda-forge/noarch::filelock-3.11.0-pyhd8ed1ab_0
  freetype           conda-forge/win-64::freetype-2.12.1-h546665d_1
  giflib             conda-forge/win-64::giflib-5.2.1-h64bf75a_3
  git                conda-forge/win-64::git-2.40.0-h57928b3_1
  idna               conda-forge/noarch::idna-3.4-pyhd8ed1ab_0
  intel-openmp       conda-forge/win-64::intel-openmp-2023.0.0-h57928b3_25922
  jinja2             conda-forge/noarch::jinja2-3.1.2-pyhd8ed1ab_1
  jpeg               conda-forge/win-64::jpeg-9e-hcfcfb64_3
  lerc               conda-forge/win-64::lerc-4.0.0-h63175ca_0
  libblas            conda-forge/win-64::libblas-3.9.0-6_mkl
  libcblas           conda-forge/win-64::libcblas-3.9.0-6_mkl
  libcublas          nvidia/label/cuda-11.7.0/win-64::libcublas-11.10.1.25-0
  libcublas-dev      nvidia/label/cuda-11.7.0/win-64::libcublas-dev-11.10.1.25-0
  libcufft           nvidia/label/cuda-11.7.0/win-64::libcufft-10.7.2.50-0
  libcufft-dev       nvidia/label/cuda-11.7.0/win-64::libcufft-dev-10.7.2.50-0
  libcurand          nvidia/label/cuda-11.7.0/win-64::libcurand-10.2.10.50-0
  libcurand-dev      nvidia/label/cuda-11.7.0/win-64::libcurand-dev-10.2.10.50-0
  libcusolver        nvidia/label/cuda-11.7.0/win-64::libcusolver-11.3.5.50-0
  libcusolver-dev    nvidia/label/cuda-11.7.0/win-64::libcusolver-dev-11.3.5.50-0
  libcusparse        nvidia/label/cuda-11.7.0/win-64::libcusparse-11.7.3.50-0
  libcusparse-dev    nvidia/label/cuda-11.7.0/win-64::libcusparse-dev-11.7.3.50-0
  libdeflate         conda-forge/win-64::libdeflate-1.17-hcfcfb64_0
  libffi             conda-forge/win-64::libffi-3.4.2-h8ffe710_5
  liblapack          conda-forge/win-64::liblapack-3.9.0-6_mkl
  liblapacke         conda-forge/win-64::liblapacke-3.9.0-6_mkl
  libnpp             nvidia/label/cuda-11.7.0/win-64::libnpp-11.7.3.21-0
  libnpp-dev         nvidia/label/cuda-11.7.0/win-64::libnpp-dev-11.7.3.21-0
  libnvjpeg          nvidia/label/cuda-11.7.0/win-64::libnvjpeg-11.7.2.34-0
  libnvjpeg-dev      nvidia/label/cuda-11.7.0/win-64::libnvjpeg-dev-11.7.2.34-0
  libpng             conda-forge/win-64::libpng-1.6.39-h19919ed_0
  libsqlite          conda-forge/win-64::libsqlite-3.40.0-hcfcfb64_0
  libtiff            conda-forge/win-64::libtiff-4.5.0-hf8721a0_2
  libuv              conda-forge/win-64::libuv-1.44.2-h8ffe710_0
  libwebp            pkgs/main/win-64::libwebp-1.2.4-hbc33d0d_1
  libwebp-base       pkgs/main/win-64::libwebp-base-1.2.4-h2bbff1b_1
  libzlib            conda-forge/win-64::libzlib-1.2.13-hcfcfb64_4
  m2w64-gcc-libgfor~ conda-forge/win-64::m2w64-gcc-libgfortran-5.3.0-6
  m2w64-gcc-libs     conda-forge/win-64::m2w64-gcc-libs-5.3.0-7
  m2w64-gcc-libs-co~ conda-forge/win-64::m2w64-gcc-libs-core-5.3.0-7
  m2w64-gmp          conda-forge/win-64::m2w64-gmp-6.1.0-2
  m2w64-libwinpthre~ conda-forge/win-64::m2w64-libwinpthread-git-5.0.0.4634.697f757-2
  markupsafe         conda-forge/win-64::markupsafe-2.1.2-py310h8d17308_0
  mkl                conda-forge/win-64::mkl-2020.4-hb70f87d_311
  mpmath             conda-forge/noarch::mpmath-1.3.0-pyhd8ed1ab_0
  msys2-conda-epoch  conda-forge/win-64::msys2-conda-epoch-20160418-1
  networkx           conda-forge/noarch::networkx-3.1-pyhd8ed1ab_0
  ninja              conda-forge/win-64::ninja-1.11.1-h91493d7_0
  nsight-compute     nvidia/label/cuda-11.7.0/win-64::nsight-compute-2022.2.0.13-0
  numpy              conda-forge/win-64::numpy-1.24.2-py310hd02465a_0
  openssl            conda-forge/win-64::openssl-3.1.0-hcfcfb64_0
  pillow             pkgs/main/win-64::pillow-9.4.0-py310hd77b12b_0
  pip                conda-forge/noarch::pip-23.1-pyhd8ed1ab_0
  pycparser          conda-forge/noarch::pycparser-2.21-pyhd8ed1ab_0
  pyopenssl          conda-forge/noarch::pyopenssl-23.1.1-pyhd8ed1ab_0
  pysocks            conda-forge/noarch::pysocks-1.7.1-pyh0701188_6
  python             conda-forge/win-64::python-3.10.10-h4de0772_0_cpython
  python_abi         conda-forge/win-64::python_abi-3.10-3_cp310
  pytorch            pytorch/win-64::pytorch-2.0.0-py3.10_cuda11.7_cudnn8_0
  pytorch-cuda       pytorch/win-64::pytorch-cuda-11.7-h16d0643_3
  pytorch-mutex      pytorch/noarch::pytorch-mutex-1.0-cuda
  requests           conda-forge/noarch::requests-2.28.2-pyhd8ed1ab_1
  setuptools         conda-forge/noarch::setuptools-67.6.1-pyhd8ed1ab_0
  sympy              conda-forge/noarch::sympy-1.11.1-pyh04b8f61_3
  tk                 conda-forge/win-64::tk-8.6.12-h8ffe710_0
  torchaudio         pytorch/win-64::torchaudio-2.0.0-py310_cu117
  torchvision        pytorch/win-64::torchvision-0.15.0-py310_cu117
  typing_extensions  conda-forge/noarch::typing_extensions-4.5.0-pyha770c72_0
  tzdata             conda-forge/noarch::tzdata-2023c-h71feb2d_0
  ucrt               conda-forge/win-64::ucrt-10.0.22621.0-h57928b3_0
  urllib3            conda-forge/noarch::urllib3-1.26.15-pyhd8ed1ab_0
  vc                 conda-forge/win-64::vc-14.3-hb6edc58_10
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.34.31931-h4c5c07a_10
  wheel              conda-forge/noarch::wheel-0.40.0-pyhd8ed1ab_0
  win_inet_pton      conda-forge/noarch::win_inet_pton-1.1.0-pyhd8ed1ab_6
  xz                 conda-forge/win-64::xz-5.2.6-h8d14728_0
  zlib               conda-forge/win-64::zlib-1.2.13-hcfcfb64_4
  zstd               conda-forge/win-64::zstd-1.5.2-h12be248_6

Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: failed

SafetyError: The package for libcusparse-dev located at C:\AI\one-click-installers-oobabooga-windows\installer_files\miniconda3\pkgs\libcusparse-dev-11.7.3.50-0
appears to be corrupted. The path 'bin/cusparse64_11.dll'
has an incorrect size.
  reported size: 232169472 bytes
  actual size: 114229248 bytes

CondaVerificationError: The package for libcusparse-dev located at C:\AI\one-click-installers-oobabooga-windows\installer_files\miniconda3\pkgs\libcusparse-dev-11.7.3.50-0
appears to be corrupted. The path 'src/cusparse_fortran.c'
specified in the package manifest cannot be found.

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: nvidia/label/cuda-11.7.0/win-64::cuda-cuobjdump-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-cupti-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-cuxxfilt-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-documentation-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-memcheck-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvcc-11.7.64-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvdisasm-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvml-dev-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvprof-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvprune-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvtx-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-sanitizer-api-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::nsight-compute-2022.2.0.13-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvvp-11.7.50-0
  path: 'license'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: nvidia/label/cuda-11.7.0/win-64::cuda-cuobjdump-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-cupti-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-cuxxfilt-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-documentation-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-memcheck-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvcc-11.7.64-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvdisasm-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvml-dev-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvprof-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvprune-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvtx-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-sanitizer-api-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::nsight-compute-2022.2.0.13-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvvp-11.7.50-0
  path: 'build_env_setup.bat'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: nvidia/label/cuda-11.7.0/win-64::cuda-cuobjdump-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-cupti-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-cuxxfilt-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-documentation-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-memcheck-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvcc-11.7.64-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvdisasm-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvml-dev-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvprof-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvprune-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvtx-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-sanitizer-api-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::nsight-compute-2022.2.0.13-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvvp-11.7.50-0
  path: 'conda_build.bat'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: nvidia/label/cuda-11.7.0/win-64::cuda-cuobjdump-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-cupti-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-cuxxfilt-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-documentation-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-memcheck-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvcc-11.7.64-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvdisasm-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvml-dev-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvprof-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvprune-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvtx-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-sanitizer-api-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::nsight-compute-2022.2.0.13-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvvp-11.7.50-0
  path: 'metadata_conda_debug.yaml'

Conda environment creation failed.
Press any key to continue . . .

**Comment by jllllll** [comment]
Just re-installed and I'm not having this issue. If I had to guess, this is likely being caused by an unstable network connection. The clobber errors were probably caused by the corrupted download error immediately preceding them:
```
SafetyError: The package for libcusparse-dev located at C:\AI\one-click-installers-oobabooga-windows\installer_files\miniconda3\pkgs\libcusparse-dev-11.7.3.50-0
appears to be corrupted. The path 'bin/cusparse64_11.dll'
has an incorrect size.
reported size: 232169472 bytes
actual size: 114229248 bytes
```

The main installers repo has been updated with a cross-platform installer that includes pretty much all of the functionality of this installer. While I'll still maintain this one, I would highly recommend switching as there are multiple people, including oobabooga, that will be maintaining that installer.

https://github.com/oobabooga/one-click-installers
