### ISSUE TITLE
Miniconda install failed

### ISSUE THREAD

**Issue by michamohe** [jllllll/one-click-installers#5]
I'm getting this error

What is your GPU?

A) NVIDIA
B) None (I want to run in CPU mode)

Input> a
Downloading Miniconda installer from https://repo.anaconda.com/miniconda/Miniconda3-py310_23.1.0-1-Windows-x86_64.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 53.1M  100 53.1M    0     0  25.8M      0  0:00:02  0:00:02 --:--:-- 25.8M

Installing Miniconda To "C:\Windows\System32\installer_files\miniconda3"
Please Wait...

Miniconda install failed.
Press any key to continue . . .

**Comment by jllllll** [comment]
Are you actually installing it in `System32` or is it just doing that on it's own?
I don't think the install will ever work properly in that folder as it has the highest security in Windows.

**Comment by michamohe** [comment]
I'm trying to install it on my NAS's hard drive through my home PC

**Comment by jllllll** [comment]
Do you have the NAS mapped to a drive letter?

If so, then on line 6 of `install.bat` change `cd /D "%~dp0"` to `cd /D "X:\OptionalSubfolder"` where `X` is the drive it is mapped to.

I have no experience with NAS so I can only assume that will work. A similar change will need to be made in the other scripts as well.

This should allow you to have the scripts located on your home PC and have them run with the files located on your NAS.

**Comment by michamohe** [comment]
ty, currently I don't but I can, I'll let you know if that fixes the issue

**Comment by Codingrocks3** [comment]
For an easy fix, if you have a second drive that you want to install this to, just move the folder to the separate drive, and it won't install to system32

**Comment by MrClams06** [comment]
I'm having a similar problem but I'm trying to run it in CPU mode because I don't have a NVIDIA GPU and it's trying to install into "\Downloads\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\miniconda3"

**Comment by jllllll** [comment]
> I'm having a similar problem but I'm trying to run it in CPU mode because I don't have a NVIDIA GPU and it's trying to install into "\Downloads\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\miniconda3"

The path you are installing to is likely too long.
