### ISSUE TITLE
Possible enhancement: using ROCm nightly (5.5)

### ISSUE THREAD

**Issue by JadeGrey** [jllllll/one-click-installers#7]
Changing the ROCm version seems to be faster (May just be a placebo):
Under `if sys.platform.startswith("linux"):`
```
run_cmd('conda install -y -k ninja git && python -m pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm5.5', assert_success=True, environment=True)
```

**Comment by jllllll** [comment]
It probably is faster. The issue with using the nightly versions is that new builds are being uploaded all the time and old builds aren't kept. This means that a broken build could be uploaded and the ROCm part of the installer would be non-functional until the Pytorch devs upload a fixed build. Personally, I think it would be better for people to choose what version they want to use and just leave the stable 2.0.1 Pytorch as the default. Pytorch 2.1 isn't too far away, so I think this will get a lot better for AMD users when that is released.

**Comment by JadeGrey** [comment]
Fair point, I will continue to use nightly, just because if something goes wrong I know how to fix it. Otherwise you'd probably get flooded with issues from others. Thanks!
