### ISSUE TITLE
Getting the following error re:pydantic

### ISSUE THREAD

**Issue by rapidarchitect** [jllllll/one-click-installers#8]
Cannot import name 'Undefined' from 'pydantic.fields
happens when i try to launch start-webui.bat

**Comment by jllllll** [comment]
I haven't had time to update the installers in this repo for a while. I'll get around to it soon.

In the mean time, try running this command with `miniconda-cmd.bat`:
```
python -m pip install fastapi==0.95.2 pydantic==1.10.12 --force-reinstall --no-deps
```
Updating the webui may also fix this as those versions are now specified in requirements.txt.

**Comment by jllllll** [comment]
There are currently some dependency conflicts in the webui that need resolving. That command will fix the error, but updating will result in needed to run that command again.

**Comment by rapidarchitect** [comment]
that fixed it thanks :)

**Comment by jllllll** [comment]
The webui has now updated to fix this issue: https://github.com/oobabooga/text-generation-webui/commit/8250d0149df86ff05fcdd0a5fb655cd325398d15

I'm working on updating the installers in this repo. Though the error you had shouldn't occur regardless.
